import { LockOutlined, ReloadOutlined, SearchOutlined, UnlockOutlined } from '@ant-design/icons';
import { PageContainer } from '@ant-design/pro-components';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { App, Button, Card, Input, Space, Table, Tag } from 'antd';
import React, { useState } from 'react';
import { getPushDevices, getTrustedDevices, revokeTrustedDevice, togglePushDevice } from '@/services/admin';
import dayjs from 'dayjs';

const DevicesPage: React.FC = () => {
  const { message } = App.useApp(); const client = useQueryClient(); const trusted = window.location.pathname.includes('trusted'); const [query, setQuery] = useState('');
  const data = useQuery({ queryKey: [trusted ? 'trusted-devices' : 'push-devices', query], queryFn: () => trusted ? getTrustedDevices(query) : getPushDevices(query) }); const rows = data.data?.devices || [];
  const action = async (work: Promise<unknown>, text: string) => { try { await work; message.success(text); client.invalidateQueries({ queryKey: [trusted ? 'trusted-devices' : 'push-devices'] }); } catch { message.error('Action could not be completed'); } };
  return <PageContainer className="admin-page" title={trusted ? 'Trusted devices' : 'Push devices'} subTitle={trusted ? 'Review and revoke trusted customer devices.' : 'Review notification registrations and delivery state.'}><Card className="resource-toolbar"><Space><Input prefix={<SearchOutlined />} allowClear value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search user or device" /><Button icon={<ReloadOutlined />} onClick={() => data.refetch()}>Refresh</Button></Space></Card><Card><Table rowKey={(row) => String(row.id)} loading={data.isLoading} dataSource={rows} columns={trusted ? [{ title: 'User', dataIndex: 'user_handle' }, { title: 'Device', dataIndex: 'device_name' }, { title: 'Platform', dataIndex: 'platform' }, { title: 'Device ID', dataIndex: 'device_id' }, { title: 'Trusted', dataIndex: 'is_trusted', render: (value) => <Tag color={value ? 'success' : 'default'}>{value ? 'Trusted' : 'Revoked'}</Tag> }, { title: 'Last seen', dataIndex: 'last_seen_at', render: (value) => dayjs(value).format('DD MMM YYYY, HH:mm') }, { title: 'Action', render: (_, row) => row.is_trusted && <Button danger icon={<LockOutlined />} onClick={() => action(revokeTrustedDevice(Number(row.id)), 'Device revoked')}>Revoke</Button> }] : [{ title: 'User', dataIndex: 'user_handle' }, { title: 'Device', dataIndex: 'device_name' }, { title: 'Platform', dataIndex: 'platform' }, { title: 'Device ID', dataIndex: 'device_id' }, { title: 'Token', dataIndex: 'token' }, { title: 'Active', dataIndex: 'active', render: (value) => <Tag color={value ? 'success' : 'default'}>{value ? 'Active' : 'Inactive'}</Tag> }, { title: 'Last seen', dataIndex: 'last_seen_at', render: (value) => dayjs(value).format('DD MMM YYYY, HH:mm') }, { title: 'Action', render: (_, row) => <Button icon={row.active ? <LockOutlined /> : <UnlockOutlined />} onClick={() => action(togglePushDevice(Number(row.id)), row.active ? 'Push device disabled' : 'Push device enabled')}>{row.active ? 'Disable' : 'Enable'}</Button> }]} pagination={{ pageSize: 15 }} scroll={{ x: 1000 }} /></Card></PageContainer>;
};
export default DevicesPage;