export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { path: '/user/login', name: 'Sign in', component: './user/login' },
      { path: '/user', redirect: '/user/login' },
      { path: '/user/*', component: './exception/404' },
    ],
  },
  {
    path: '/',
    name: 'operations',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      { path: '/', redirect: '/overview' },
      { path: '/overview', name: 'operations.overview', icon: 'dashboard', component: './admin' },
      { path: '/users', name: 'operations.users', icon: 'team', component: './admin/users' },
      { path: '/wallets', name: 'operations.wallets', icon: 'wallet', component: './admin/resource' },
      { path: '/transactions', name: 'operations.transactions', icon: 'transaction', component: './admin/transactions' },
      { path: '/requests', name: 'Payment requests', icon: 'fileText', component: './admin/records' },
      { path: '/splits', name: 'Bill splits', icon: 'partition', component: './admin/records' },
      { path: '/attempts', name: 'Transfer attempts', icon: 'warning', component: './admin/records' },
      { path: '/audit', name: 'Audit trail', icon: 'audit', component: './admin/records' },
      { path: '/settings', name: 'Platform settings', icon: 'setting', component: './admin/records' },
      { path: '/tasks', name: 'Scheduled tasks', icon: 'schedule', component: './admin/operations' },
      { path: '/support', name: 'Support tickets', icon: 'customerService', component: './admin/support' },
      { path: '/kyc', name: 'KYC review', icon: 'safetyCertificate', component: './admin/kyc' },
      { path: '/mobile-money', name: 'Mobile money', icon: 'mobile', component: './admin/operations' },
      { path: '/webhooks', name: 'Failed webhooks', icon: 'api', component: './admin/operations' },
      { path: '/fee-rules', name: 'Transfer fee rules', icon: 'payCircle', component: './admin/finance' },
      { path: '/rates', name: 'Exchange rates', icon: 'fund', component: './admin/finance' },
      { path: '/team', name: 'Admin team', icon: 'usergroupAdd', component: './admin/records' },
      { path: '/push-devices', name: 'operations.push-devices', icon: 'notification', component: './admin/devices' },
      { path: '/trusted-devices', name: 'operations.trusted-devices', icon: 'mobile', component: './admin/devices' },
      { path: '/parental-controls', name: 'operations.parental-controls', icon: 'safety', component: './admin/parental' },
      { path: '/disputes', name: 'Disputes', icon: 'exception', component: './admin/records' },
      { path: '/merchants', name: 'Merchants', icon: 'shop', component: './admin/merchants' },
    ],
  },
  { path: '/*', component: './exception/404' },
];
