# Generated by Django 5.1.5 on 2026-08-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallet.transaction'),
        ),
    ]
