# Generated by Django 5.1.5 on 2026-08-13 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_ledgerentry_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exchange_rates',
            },
        ),
        migrations.CreateModel(
            name='LinkedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN MoMo'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money')], max_length=20)),
                ('masked_reference', models.CharField(max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'linked_providers',
            },
        ),
        migrations.CreateModel(
            name='TransferAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_handle_input', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('rejection_reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transfer_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('p2p_transfer', 'P2P Transfer'), ('reversal', 'Reversal'), ('topup', 'Top-up'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', 'created_at'], name='ledger_entr_wallet__d8f5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'valid_from'], name='exchange_ra_from_cu_4ac092_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'valid_from')},
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.exchangerate'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sender', 'created_at'], name='transaction_sender__34b6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['recipient', 'created_at'], name='transaction_recipie_54a7ee_idx'),
        ),
        migrations.AddField(
            model_name='linkedprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='linkedprovider',
            index=models.Index(fields=['user', 'provider'], name='linked_prov_user_id_ee2ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedprovider',
            index=models.Index(fields=['verification_status'], name='linked_prov_verific_c2e3f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkedprovider',
            unique_together={('user', 'provider')},
        ),
        migrations.AddIndex(
            model_name='transferattempt',
            index=models.Index(fields=['user', 'created_at'], name='transfer_at_user_id_5096c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transferattempt',
            index=models.Index(fields=['rejection_reason', 'created_at'], name='transfer_at_rejecti_940da8_idx'),
        ),
    ]
