# Generated by Django 5.1.5 on 2026-08-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_paymentrequest_splitrequest_splitparticipant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentrequest',
            new_name='payment_req_request_35db71_idx',
            old_name='payment_req_request_26a1ee_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrequest',
            new_name='payment_req_payer_i_ec2ab7_idx',
            old_name='payment_req_payer_i_0cc8f0_idx',
        ),
    ]
