# Generated by Django 5.1.5 on 2026-08-16 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_splitrequest_cancellation_reason_splitrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_reversed', 'Resolved (Reversed)'), ('resolved_denied', 'Resolved (Denied)')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='wallet.transaction')),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opened_by', 'status', 'created_at'], name='disputes_opened__d2f5c5_idx'), models.Index(fields=['status', 'created_at'], name='disputes_status_536461_idx'), models.Index(fields=['transaction'], name='disputes_transac_6a360f_idx')],
            },
        ),
    ]
