# Generated by Django 5.1.5 on 2026-08-16 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_dispute'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'Top-up'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobile_money_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='dispute',
            name='disputes_status_536461_idx',
        ),
        migrations.RemoveIndex(
            model_name='dispute',
            name='disputes_transac_6a360f_idx',
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['transaction', 'status'], name='disputes_transac_13ac54_idx'),
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='linked_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_money_transactions', to='wallet.linkedprovider'),
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transactions', to='wallet.wallet'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['user', 'status', 'created_at'], name='mobile_mone_user_id_28494c_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['linked_provider', 'status'], name='mobile_mone_linked__751501_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['provider_transaction_id'], name='mobile_mone_provide_acb64d_idx'),
        ),
    ]
