# Generated by Django 5.1.5 on 2026-08-16 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_mobilemoneytransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_execution', models.DateTimeField()),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('total_executions', models.IntegerField(default=0)),
                ('max_executions', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_scheduled_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_transfers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status', 'next_execution'], name='scheduled_t_sender__104ecf_idx'), models.Index(fields=['status', 'next_execution'], name='scheduled_t_status_8539b7_idx')],
            },
        ),
    ]
