# Generated by Django 5.1.5 on 2026-08-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_scheduledtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('static_qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('static_qr_payload', models.TextField(blank=True, default='')),
                ('static_qr_signature', models.CharField(blank=True, default='', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_id', models.CharField(blank=True, default='', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_merchants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_account', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_accounts', to='wallet.wallet')),
            ],
            options={
                'db_table': 'merchants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='merchants_user_id_48d0a4_idx'), models.Index(fields=['status', 'created_at'], name='merchants_status_840714_idx'), models.Index(fields=['static_qr_code'], name='merchants_static__7e1652_idx')],
            },
        ),
    ]
