# Generated by Django 5.2.1 on 2026-08-17 21:20

import django.db.models.deletion
import wallet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='business_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='merchant',
            name='mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10),
        ),
        migrations.AddField(
            model_name='merchant',
            name='sandbox_wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox_merchant_account', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='merchant',
            name='webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='merchant',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('applies_to', models.CharField(choices=[('p2p_transfer', 'P2P Transfer'), ('merchant_transfer', 'Merchant Transfer')], max_length=30)),
                ('fee_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fee_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_policies', to='wallet.merchant')),
            ],
            options={
                'db_table': 'fee_policies',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to', models.CharField(choices=[('p2p_transfer', 'P2P Transfer'), ('merchant_transfer', 'Merchant Transfer')], max_length=30)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fee_waivers',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, default='')),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending_payment', 'Pending Payment'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10)),
                ('return_url', models.URLField(blank=True, default='')),
                ('expires_at', models.DateTimeField(default=wallet.models.default_payment_intent_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='wallet.merchant')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('resulting_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='wallet.transaction')),
            ],
            options={
                'db_table': 'payment_intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('target_url', models.URLField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='wallet.merchant')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='wallet.paymentintent')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10)),
                ('public_key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('secret_key_prefix', models.CharField(db_index=True, max_length=20)),
                ('secret_key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='wallet.merchant')),
            ],
            options={
                'db_table': 'merchant_api_keys',
                'indexes': [models.Index(fields=['secret_key_prefix', 'is_active'], name='merchant_ap_secret__8badb6_idx')],
                'unique_together': {('merchant', 'mode')},
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['merchant', 'status', 'created_at'], name='payment_int_merchan_800dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'expires_at'], name='payment_int_status_30688e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['external_reference'], name='payment_int_externa_b15e33_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['merchant', 'status', 'created_at'], name='webhook_del_merchan_ac9975_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['payment_intent', 'event_type'], name='webhook_del_payment_ba99ab_idx'),
        ),
    ]
