# Generated by Django 5.2.1 on 2026-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_usage_based_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
