# Generated by Django 5.2.1 on 2026-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Primary phone number for transfers and payments', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='default_provider',
            field=models.CharField(default='orange_money', help_text='Default mobile money provider for this wallet (orange_money, mtn_momo, airtel_money)', max_length=20),
        ),
    ]
