# Generated by Django 5.2.1 on 2026-09-08 11:54

import django.db.models.deletion
import wallet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_user_primary_phone_number_wallet_default_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('approval_type', models.CharField(help_text='Type of approval: money_received, payment_request, split_bill', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(default=wallet.models.default_request_expiry)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_delivered', models.BooleanField(default=False)),
                ('webhook_delivery_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_approvals', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='wallet.paymentrequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_approvals', to=settings.AUTH_USER_MODEL)),
                ('split_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='wallet.splitrequest')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='wallet.transaction')),
            ],
            options={
                'db_table': 'transaction_approvals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approver', 'status', 'created_at'], name='transaction_approve_ef6c4d_idx'), models.Index(fields=['requester', 'status', 'created_at'], name='transaction_request_c946f1_idx'), models.Index(fields=['status', 'expires_at'], name='transaction_status_d560b4_idx')],
            },
        ),
    ]
