# Generated by Django 5.2.1 on 2026-09-08 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_transactionapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='4-digit PIN for transaction approvals', max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='ParentalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('verification_code', models.CharField(help_text="6-digit code sent to child's device for verification", max_length=6)),
                ('code_expires_at', models.DateTimeField(help_text='When the verification code expires')),
                ('linked_at', models.DateTimeField(blank=True, help_text='When the parental control was successfully linked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_view_transactions', models.BooleanField(default=True, help_text="Parent can view child's transactions")),
                ('can_control_balance', models.BooleanField(default=True, help_text="Parent can control child's balance")),
                ('can_send_money', models.BooleanField(default=True, help_text='Parent can send money to child')),
                ('can_set_limits', models.BooleanField(default=True, help_text="Parent can set child's spending limits")),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parental Control',
                'verbose_name_plural': 'Parental Controls',
                'db_table': 'parental_controls',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
