# Generated by Django 5.2.1 on 2026-09-10 11:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_configuration(apps, schema_editor):
    SupportedCountry = apps.get_model('wallet', 'SupportedCountry')
    LegalDocument = apps.get_model('wallet', 'LegalDocument')
    ProviderCatalog = apps.get_model('wallet', 'ProviderCatalog')
    TransferFeeRule = apps.get_model('wallet', 'TransferFeeRule')
    for code, name, dial_code in [
        ('GN', 'Guinea', '+224'), ('SN', 'Senegal', '+221'), ('CI', 'Cote d Ivoire', '+225'),
        ('GH', 'Ghana', '+233'), ('NG', 'Nigeria', '+234'), ('KE', 'Kenya', '+254'),
    ]:
        SupportedCountry.objects.get_or_create(code=code, defaults={'name': name, 'dial_code': dial_code})
    LegalDocument.objects.get_or_create(
        slug='terms-and-conditions',
        defaults={'title': 'Terms and Conditions', 'body_html': '<h1>Terms and Conditions</h1><p>Use of DSD PAY is subject to these terms.</p>'},
    )
    for sort_order, code, name in [(1, 'mtn_momo', 'MTN MoMo'), (2, 'airtel_money', 'Airtel Money'), (3, 'orange_money', 'Orange Money')]:
        ProviderCatalog.objects.get_or_create(code=code, defaults={'name': name, 'sort_order': sort_order})
    TransferFeeRule.objects.get_or_create(min_amount=0, max_amount=None, defaults={'fee_type': 'percentage', 'fee_value': 0})


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_payment_request_two_minute_expiry'),
    ]

    operations = [
        migrations.RunPython(seed_configuration, migrations.RunPython.noop),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dial_code', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransferFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fee_type', models.CharField(choices=[('flat', 'Flat amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('fee_value', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='UserKYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=40)),
                ('document', models.FileField(upload_to='kyc/users/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
