# Generated by Django 5.2.1 on 2026-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_legaldocument_providercatalog_supportedcountry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedcountry',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
