# Generated by Django 5.2.1 on 2026-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_supportedcountry_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionapproval',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='current_device_id',
            field=models.CharField(blank=True, db_index=True, help_text='Single active device login token', max_length=255, null=True),
        ),
    ]
