# Generated by Django 5.2.1 on 2026-09-13 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0030_pushdevice_device_id_supportticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('provider_transaction_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('signature', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobile_money_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_trusted', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_devices',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('provider_link', 'Provider link'), ('admin_login', 'Admin login')], max_length=30)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_challenges', to='wallet.trusteddevice')),
            ],
            options={
                'db_table': 'otp_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='otp_challen_user_id_4bd70e_idx'), models.Index(fields=['expires_at', 'consumed_at'], name='otp_challen_expires_6b0feb_idx')],
            },
        ),
    ]
