import { AuditOutlined, CheckCircleOutlined, ClockCircleOutlined, DollarOutlined, FileSearchOutlined, LockOutlined, ReloadOutlined, SafetyCertificateOutlined, SearchOutlined, TeamOutlined, TransactionOutlined, UnlockOutlined, UserOutlined, WalletOutlined } from '@ant-design/icons';
import { PageContainer } from '@ant-design/pro-components';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { App, Avatar, Button, Card, Col, Descriptions, Drawer, Empty, Input, Modal, Row, Segmented, Space, Statistic, Table, Tag, Tabs, Tooltip, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';
import React, { useState } from 'react';
import { freezeWallet, getAuditLog, getCrudWallets, getDashboard, getKycSubmissions, getSupportTickets, getTransactions, getUsers, refreshRates, reviewKyc, runReconciliation, updateUser } from '@/services/admin';
import type { AdminTransaction, AdminUser } from '@/services/admin';
import './style.css';

const statusColor: Record<string, string> = { active: 'success', completed: 'success', approved: 'success', pending: 'warning', suspended: 'error', frozen: 'error', failed: 'error', rejected: 'error' };
const display = (value: unknown) => typeof value === 'object' && value !== null ? ((value as { handle?: string }).handle || '-') : String(value || '-');
const date = (value?: string) => value ? dayjs(value).format('DD MMM YYYY, HH:mm') : '-';

const AdminDashboard: React.FC = () => {
  const { message } = App.useApp();
  const queryClient = useQueryClient();
  const [active, setActive] = useState('overview');
  const [query, setQuery] = useState('');
  const [userDrawer, setUserDrawer] = useState<AdminUser | null>(null);
  const [reviewing, setReviewing] = useState<Record<string, unknown> | null>(null);
  const dashboard = useQuery({ queryKey: ['admin-dashboard'], queryFn: getDashboard });
  const users = useQuery({ queryKey: ['admin-users', query], queryFn: () => getUsers({ query, page_size: 50 }), enabled: active === 'users' || active === 'overview' });
  const transactions = useQuery({ queryKey: ['admin-transactions', query], queryFn: () => getTransactions({ query, page_size: 50 }), enabled: active === 'transactions' });
  const wallets = useQuery({ queryKey: ['admin-wallets'], queryFn: getCrudWallets, enabled: active === 'wallets' });
  const kyc = useQuery({ queryKey: ['admin-kyc'], queryFn: () => getKycSubmissions(), enabled: active === 'compliance' });
  const tickets = useQuery({ queryKey: ['admin-tickets'], queryFn: () => getSupportTickets({}), enabled: active === 'support' });
  const audit = useQuery({ queryKey: ['admin-audit'], queryFn: getAuditLog, enabled: active === 'audit' });
  const stats = dashboard.data;
  const refresh = () => queryClient.invalidateQueries({ queryKey: [`admin-${active === 'overview' ? 'dashboard' : active}`] });
  const action = async (work: Promise<unknown>, success: string) => { try { await work; message.success(success); refresh(); } catch { message.error('Action could not be completed.'); } };
  const userColumns: ColumnsType<AdminUser> = [{ title: 'User', render: (_, record) => <Space><Avatar size="small" icon={<UserOutlined />} /><div><Typography.Text strong>{record.display_name || record.handle || 'Unnamed user'}</Typography.Text><br /><Typography.Text type="secondary">{record.email || record.primary_phone_number}</Typography.Text></div></Space> }, { title: 'Status', dataIndex: 'status', render: (value) => <Tag color={statusColor[value] || 'default'}>{value}</Tag> }, { title: 'KYC', dataIndex: 'kyc_tier', render: (value) => <Tag>{value || 'tier_0'}</Tag> }, { title: 'Joined', dataIndex: 'created_at', render: date }, { title: 'Actions', render: (_, record) => <Space><Button type="link" onClick={() => setUserDrawer(record)}>View</Button><Tooltip title="Freeze or unfreeze wallet"><Button icon={record.wallet?.status === 'frozen' ? <UnlockOutlined /> : <LockOutlined />} onClick={() => Modal.confirm({ title: 'Change wallet status?', content: 'A reason is required for the audit trail.', onOk: () => action(freezeWallet(record.id, 'Admin dashboard action'), 'Wallet status updated') })} /></Tooltip></Space> }];
  const transactionColumns: ColumnsType<AdminTransaction> = [{ title: 'Reference', dataIndex: 'id', ellipsis: true }, { title: 'Type', dataIndex: 'type', render: (value) => <Tag>{value}</Tag> }, { title: 'From', dataIndex: 'sender', render: display }, { title: 'To', dataIndex: 'recipient', render: display }, { title: 'Amount', render: (_, r) => <Typography.Text strong>{r.amount} {r.currency}</Typography.Text> }, { title: 'Status', dataIndex: 'status', render: (value) => <Tag color={statusColor[value] || 'default'}>{value}</Tag> }, { title: 'Created', dataIndex: 'created_at', render: date }];
  const tableData = (data: unknown) => Array.isArray(data) ? data : (data as { results?: unknown[] })?.results || [];
  const tabs = [{ key: 'overview', label: 'Overview', icon: <TransactionOutlined /> }, { key: 'users', label: 'Users', icon: <TeamOutlined /> }, { key: 'wallets', label: 'Wallets', icon: <WalletOutlined /> }, { key: 'transactions', label: 'Transactions', icon: <DollarOutlined /> }, { key: 'compliance', label: 'KYC review', icon: <SafetyCertificateOutlined /> }, { key: 'support', label: 'Support', icon: <FileSearchOutlined /> }, { key: 'audit', label: 'Audit trail', icon: <AuditOutlined /> }];
  return <PageContainer className="admin-page" title="Operations control room" subTitle="A complete view of wallet activity, risk, and platform health" extra={<Space><Button icon={<ReloadOutlined />} onClick={refresh}>Refresh</Button><Button type="primary" onClick={() => action(runReconciliation(), 'Reconciliation queued')}>Run reconciliation</Button></Space>}>
    <div className="admin-hero"><div><Typography.Text className="eyebrow">WALLE RT / ADMIN</Typography.Text><Typography.Title level={1}>Good morning, admin.</Typography.Title><Typography.Paragraph>Keep the ledger clean, resolve the exceptions, and give every customer a fast answer.</Typography.Paragraph></div><div className="hero-mark"><CheckCircleOutlined /></div></div>
    <Tabs activeKey={active} onChange={(key) => { setActive(key); setQuery(''); }} items={tabs} className="admin-tabs" />
    {active === 'overview' && <><Row gutter={[16, 16]} className="metric-row">{[[TeamOutlined, 'Active users', stats?.active_users, `of ${stats?.total_users || 0} total`], [DollarOutlined, 'P2P volume today', stats?.p2p_volume_today || '0', 'GNF settled'], [ClockCircleOutlined, 'Pending requests', stats?.pending_payment_requests, 'need attention'], [LockOutlined, 'Frozen wallets', stats?.frozen_wallets, 'risk controls']].map(([Icon, label, value, note]) => <Col xs={24} sm={12} lg={6} key={String(label)}><Card className="metric-card"><Avatar className="metric-icon" icon={React.createElement(Icon as React.ElementType)} /><Statistic title={label as string} value={value as React.Key} /><Typography.Text type="secondary">{note as string}</Typography.Text></Card></Col>)}</Row><Row gutter={[16, 16]} className="overview-grid"><Col xs={24} lg={15}><Card title="Latest users" extra={<Button type="link" onClick={() => setActive('users')}>View all</Button>}><Table rowKey="id" size="small" pagination={false} loading={users.isLoading} columns={userColumns.slice(0, 4)} dataSource={tableData(users.data)} /></Card></Col><Col xs={24} lg={9}><Card title="Control centre"><Space direction="vertical" size="middle" className="quick-actions"><Button block icon={<SafetyCertificateOutlined />} onClick={() => setActive('compliance')}>Review pending KYC</Button><Button block icon={<FileSearchOutlined />} onClick={() => setActive('support')}>Open support queue</Button><Button block icon={<ReloadOutlined />} onClick={() => action(refreshRates(), 'Exchange-rate refresh queued')}>Refresh exchange rates</Button></Space><Descriptions column={1} size="small" className="health-list"><Descriptions.Item label="7-day volume">{stats?.p2p_volume_week || '0'} GNF</Descriptions.Item><Descriptions.Item label="Rejected attempts (24h)">{stats?.transfer_attempt_rejections_24h || 0}</Descriptions.Item><Descriptions.Item label="Wallet coverage">{stats?.total_wallets || 0} wallets</Descriptions.Item></Descriptions></Card></Col></Row></>}
    {active === 'users' && <Card title="Customer accounts" extra={<Input allowClear prefix={<SearchOutlined />} placeholder="Search handle, email, phone" value={query} onChange={(e) => setQuery(e.target.value)} style={{ width: 280 }} />}><Table rowKey="id" loading={users.isLoading} columns={userColumns} dataSource={tableData(users.data) as AdminUser[]} pagination={{ pageSize: 15, showSizeChanger: true }} /></Card>}
    {active === 'transactions' && <Card title="Ledger activity" extra={<Input allowClear prefix={<SearchOutlined />} placeholder="Search transaction or handle" value={query} onChange={(e) => setQuery(e.target.value)} style={{ width: 280 }} />}><Table rowKey="id" loading={transactions.isLoading} columns={transactionColumns} dataSource={tableData(transactions.data) as AdminTransaction[]} pagination={{ pageSize: 15 }} scroll={{ x: 900 }} /></Card>}
    {active === 'wallets' && <Card title="Wallet accounts"><Table rowKey="id" loading={wallets.isLoading} dataSource={wallets.data || []} columns={[{ title: 'Wallet', dataIndex: 'id' }, { title: 'User', dataIndex: 'user' }, { title: 'Currency', dataIndex: 'currency' }, { title: 'Balance', dataIndex: 'balance' }, { title: 'Status', dataIndex: 'status', render: (value) => <Tag color={statusColor[value] || 'default'}>{value}</Tag> }]} pagination={{ pageSize: 15 }} /></Card>}
    {active === 'compliance' && <Card title="Identity verification queue" extra={<Segmented options={['Pending', 'Approved', 'Rejected']} defaultValue="Pending" />}><Table rowKey={(r) => String(r.id)} loading={kyc.isLoading} dataSource={kyc.data?.submissions || []} columns={[{ title: 'Applicant', render: (_, r) => display((r as { user?: unknown }).user) }, { title: 'Document', dataIndex: 'document_type' }, { title: 'Submitted', dataIndex: 'created_at', render: date }, { title: 'Status', dataIndex: 'status', render: (value) => <Tag color={statusColor[value] || 'default'}>{value}</Tag> }, { title: 'Review', render: (_, record) => <Button type="link" onClick={() => setReviewing(record)}>Open review</Button> }]} pagination={{ pageSize: 15 }} /></Card>}
    {active === 'support' && <Card title="Support queue"><Table rowKey={(r) => String(r.id)} loading={tickets.isLoading} dataSource={tickets.data?.tickets || []} columns={[{ title: 'Ticket', dataIndex: 'ticket_number' }, { title: 'Subject', dataIndex: 'subject' }, { title: 'Category', dataIndex: 'category' }, { title: 'Priority', dataIndex: 'priority', render: (value) => <Tag color={value === 'urgent' ? 'red' : 'blue'}>{value}</Tag> }, { title: 'Status', dataIndex: 'status', render: (value) => <Tag color={statusColor[value] || 'default'}>{value}</Tag> }, { title: 'Updated', dataIndex: 'updated_at', render: date }]} pagination={{ pageSize: 15 }} /></Card>}
    {active === 'audit' && <Card title="Immutable audit trail"><Table rowKey={(r) => String(r.id)} loading={audit.isLoading} dataSource={tableData(audit.data)} columns={[{ title: 'Actor', render: (_, r) => display((r as { user?: unknown }).user) }, { title: 'Action', dataIndex: 'action' }, { title: 'Metadata', dataIndex: 'metadata', render: (value) => <Typography.Text code>{JSON.stringify(value)}</Typography.Text> }, { title: 'When', dataIndex: 'created_at', render: date }]} pagination={{ pageSize: 15 }} /></Card>}
    <Drawer title="User account" open={Boolean(userDrawer)} onClose={() => setUserDrawer(null)} width={440}>{userDrawer && <><Descriptions bordered column={1} items={[['Name', userDrawer.display_name || userDrawer.handle], ['Email', userDrawer.email], ['Status', userDrawer.status], ['KYC tier', userDrawer.kyc_tier], ['Created', date(userDrawer.created_at)]].map(([label, children]) => ({ label, children }))} /><Button block className="drawer-action" onClick={() => Modal.confirm({ title: 'Suspend this user?', onOk: () => action(updateUser(userDrawer.id, { status: 'suspended' }), 'User updated') })}>Suspend account</Button></>}</Drawer>
    <Modal title="KYC review" open={Boolean(reviewing)} onCancel={() => setReviewing(null)} footer={[<Button key="reject" danger onClick={() => reviewing && action(reviewKyc(Number(reviewing.id), { action: 'reject', reviewer_notes: 'Rejected from admin dashboard' }), 'KYC rejected').then(() => setReviewing(null))}>Reject</Button>, <Button key="approve" type="primary" onClick={() => reviewing && action(reviewKyc(Number(reviewing.id), { action: 'approve', target_kyc_tier: 'tier_1' }), 'KYC approved').then(() => setReviewing(null))}>Approve</Button>]}>{reviewing ? <Descriptions column={1} items={Object.entries(reviewing).slice(0, 8).map(([label, children]) => ({ label, children: typeof children === 'object' ? JSON.stringify(children) : String(children) }))} /> : <Empty />}</Modal>
  </PageContainer>;
};
export default AdminDashboard;