export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { path: '/user/login', name: 'Sign in', component: './user/login' },
      { path: '/user', redirect: '/user/login' },
      { path: '/user/*', component: './exception/404' },
    ],
  },
  {
    path: '/admin',
    name: 'Wallet administration',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      { path: '/admin', redirect: '/admin/overview' },
      { path: '/admin/overview', name: 'Overview', icon: 'dashboard', component: './admin' },
      { path: '/admin/users', name: 'Users', icon: 'team', component: './admin/users' },
      { path: '/admin/wallets', name: 'Wallets', icon: 'wallet', component: './admin/resource' },
      { path: '/admin/transactions', name: 'Transactions', icon: 'transaction', component: './admin/transactions' },
      { path: '/admin/requests', name: 'Payment requests', icon: 'fileText', component: './admin/records' },
      { path: '/admin/splits', name: 'Bill splits', icon: 'partition', component: './admin/records' },
      { path: '/admin/attempts', name: 'Transfer attempts', icon: 'warning', component: './admin/records' },
      { path: '/admin/audit', name: 'Audit trail', icon: 'audit', component: './admin/records' },
      { path: '/admin/settings', name: 'Platform settings', icon: 'setting', component: './admin/records' },
      { path: '/admin/tasks', name: 'Scheduled tasks', icon: 'schedule', component: './admin/operations' },
      { path: '/admin/support', name: 'Support tickets', icon: 'customerService', component: './admin/support' },
      { path: '/admin/kyc', name: 'KYC review', icon: 'safetyCertificate', component: './admin/kyc' },
      { path: '/admin/mobile-money', name: 'Mobile money', icon: 'mobile', component: './admin/operations' },
      { path: '/admin/webhooks', name: 'Failed webhooks', icon: 'api', component: './admin/operations' },
      { path: '/admin/fee-rules', name: 'Transfer fee rules', icon: 'payCircle', component: './admin/finance' },
      { path: '/admin/rates', name: 'Exchange rates', icon: 'fund', component: './admin/finance' },
      { path: '/admin/team', name: 'Admin team', icon: 'usergroupAdd', component: './admin/records' },
      { path: '/admin/disputes', name: 'Disputes', icon: 'exception', component: './admin/records' },
      { path: '/admin/merchants', name: 'Merchants', icon: 'shop', component: './admin/merchants' },
    ],
  },
  { path: '/', redirect: '/admin/overview' },
  { path: '/*', component: './exception/404' },
];
