"""
Django settings for walletmvp project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def getenv_bool(key: str, default: bool) -> bool:
    value = os.getenv(key)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def getenv_list(key: str, default):
    value = os.getenv(key)
    if not value:
        return default
    return [item.strip() for item in value.split(',') if item.strip()]

# HARDCODED SETTINGS FOR RENDER DEPLOYMENT
# Backend URL: https://wallet-backend-lqhq.onrender.com
# Frontend URL: https://dsd-wallet.vercel.app

# Django Configuration
SECRET_KEY = 'django-insecure-change-this-to-a-secure-random-key-in-production-12345'
DEBUG = False
ALLOWED_HOSTS = [
    'wallet-backend-lqhq.onrender.com',
    'www.wallet-backend-lqhq.onrender.com',
    'localhost',
    '127.0.0.1',
]

# Database Configuration - SQLite for now
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# CORS Configuration
FRONTEND_ORIGIN = os.getenv('FRONTEND_ORIGIN', 'https://dsd-wallet.vercel.app')

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = getenv_bool('SESSION_COOKIE_SECURE', True)
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'None')
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_AGE = 2592000  # 30 days
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_REFRESH_AT_REQUEST = True

# CSRF Configuration
CSRF_COOKIE_SECURE = getenv_bool('CSRF_COOKIE_SECURE', True)
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'None')
CSRF_COOKIE_HTTPONLY = True
CSRF_TRUSTED_ORIGINS = getenv_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'https://dsd-wallet.vercel.app',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ],
)

# Exempt API endpoints from CSRF protection (they use session auth which is sufficient)
CSRF_EXEMPT_URLS = [
    r'^/api/',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'wallet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'walletmvp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'walletmvp.wsgi.application'


# Database Configuration - HARDCODED FOR RENDER DEPLOYMENT
# Using SQLite for now
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Custom user model
AUTH_USER_MODEL = 'wallet.User'


# Password validation - disabled since we use Google OAuth only
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/staticfiles/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    # Removed DEFAULT_PERMISSION_CLASSES to allow explicit permission per view
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'wallet.exceptions.custom_exception_handler',
}

# Disable throttling in tests
import sys
TESTING = 'test' in sys.argv or 'pytest' in sys.argv
if TESTING:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []

# DRF Spectacular configuration for OpenAPI schema
SPECTACULAR_SETTINGS = {
    'TITLE': 'Wallet MVP API',
    'DESCRIPTION': 'P2P wallet backend for Venmo-style payments',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Authentication'},
        {'name': 'Users'},
        {'name': 'Transfers'},
        {'name': 'Wallet'},
        {'name': 'Notifications'},
        {'name': 'Admin'},
    ],
}


# CORS configuration
CORS_ALLOWED_ORIGINS = getenv_list(
    'CORS_ALLOWED_ORIGINS',
    [
        'https://dsd-wallet.vercel.app',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ],
)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'https://.*\.vercel\.app$',
]
CORS_ALLOW_CREDENTIALS = True

# For OAuth redirect URI
FRONTEND_ORIGIN_URL = os.getenv('FRONTEND_ORIGIN_URL', 'https://dsd-wallet.vercel.app')


# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = getenv_bool('SESSION_COOKIE_SECURE', True)
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'None')
SESSION_COOKIE_DOMAIN = None  # Let browser determine domain
SESSION_COOKIE_AGE = 2592000  # 30 days (30 * 24 * 60 * 60)
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_REFRESH_AT_REQUEST = True  # Refresh session on each activity

# CSRF configuration
# For cross-origin API with session authentication, we disable CSRF for API endpoints
# Session cookies provide sufficient protection for this use case
CSRF_COOKIE_SECURE = getenv_bool('CSRF_COOKIE_SECURE', True)
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'None')
CSRF_COOKIE_HTTPONLY = True
CSRF_TRUSTED_ORIGINS = getenv_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'https://dsd-wallet.vercel.app',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ],
)

# Exempt API endpoints from CSRF protection (they use session auth which is sufficient)
CSRF_EXEMPT_URLS = [
    r'^/api/',
]


# Google OAuth configuration - HARDCODED FOR RENDER DEPLOYMENT
GOOGLE_CLIENT_ID = '256666248694-iocf5uppdg0n9sq5i2krtp96bp80nio7.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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'
